# Generated by Django 4.1.5 on 2023-11-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=200)),
                ('fromCity', models.CharField(max_length=100)),
                ('toCity', models.CharField(max_length=100)),
                ('pkg_title', models.CharField(default='', max_length=100)),
                ('depatureDate', models.DateField()),
                ('days', models.IntegerField(default=1)),
                ('noOfRooms', models.IntegerField()),
                ('noOfAdults', models.IntegerField()),
                ('noOfChildren', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=12)),
                ('amountPerPerson', models.IntegerField(default=0)),
                ('totalAmount', models.FloatField(default=0)),
                ('userName', models.CharField(default='', max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('cancel', models.BooleanField(default=0)),
                ('cancel_reason', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.BooleanField(default=False)),
                ('Domestic', models.BooleanField(default=0)),
                ('International', models.BooleanField(default=0)),
                ('pkg_type', models.CharField(max_length=30)),
                ('pkg_title', models.CharField(max_length=30)),
                ('dep_date', models.DateField()),
                ('pkg_from', models.CharField(max_length=20)),
                ('pkg_to', models.CharField(max_length=20)),
                ('pkg_pic', models.ImageField(default='package.jpg', upload_to='package_imgs')),
                ('pkg_dec', models.TextField()),
                ('pkg_price', models.IntegerField()),
                ('pkg_days', models.IntegerField()),
                ('pkg_night', models.IntegerField()),
                ('day1_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day1_desc', models.TextField(blank=True, null=True)),
                ('day2_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day2_desc', models.TextField(blank=True, null=True)),
                ('day3_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day3_desc', models.TextField(blank=True, null=True)),
                ('day4_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day4_desc', models.TextField(blank=True, null=True)),
                ('day5_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day5_desc', models.TextField(blank=True, null=True)),
                ('day6_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day6_desc', models.TextField(blank=True, null=True)),
                ('day7_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day7_desc', models.TextField(blank=True, null=True)),
                ('day8_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day8_desc', models.TextField(blank=True, null=True)),
                ('day9_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day9_desc', models.TextField(blank=True, null=True)),
                ('day10_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day10_desc', models.TextField(blank=True, null=True)),
                ('day11_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day11_desc', models.TextField(blank=True, null=True)),
                ('day12_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day12_desc', models.TextField(blank=True, null=True)),
                ('day13_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day13_desc', models.TextField(blank=True, null=True)),
                ('day14_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day14_desc', models.TextField(blank=True, null=True)),
                ('day15_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day15_desc', models.TextField(blank=True, null=True)),
                ('day16_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day16_desc', models.TextField(blank=True, null=True)),
                ('pkg_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_by_customer_num', to='dian.confirmbooking', verbose_name='Customer Number')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_by_customer_name', to='dian.confirmbooking', verbose_name='Customer Name')),
            ],
        ),
    ]
