# Generated by Django 4.1.5 on 2023-04-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_packages_delete_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
