# Generated by Django 4.1.5 on 2023-04-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_packages_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='pkg_img',
            field=models.ImageField(default='destination.jpg', upload_to='pics'),
        ),
    ]
