# Generated by Django 4.1.5 on 2023-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_remove_packages_pkg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='avil_seats',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='tota_seats',
        ),
        migrations.AddField(
            model_name='packages',
            name='Domestic',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='packages',
            name='International',
            field=models.BooleanField(default=1),
        ),
    ]
