# Generated by Django 4.1.5 on 2023-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_packages_avil_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='pkg_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
