# Generated by Django 4.1.5 on 2023-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Domestic',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='packages',
            name='International',
            field=models.BooleanField(default=0),
        ),
    ]
