# Generated by Django 4.1.5 on 2023-04-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destination_domestic_destination_international'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_type', models.CharField(max_length=30)),
                ('pkg_title', models.CharField(max_length=30)),
                ('dep_date', models.DateField()),
                ('pkg_from', models.CharField(max_length=20)),
                ('pkg_to', models.CharField(max_length=20)),
                ('pkg_pic', models.ImageField(default='package.jpg', upload_to='package_imgs')),
                ('pkg_dec', models.TextField()),
                ('pkg_price', models.IntegerField()),
                ('pkg_days', models.IntegerField()),
                ('pkg_night', models.IntegerField()),
                ('tota_seats', models.IntegerField()),
                ('avil_seats', models.IntegerField()),
                ('day1_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day1_desc', models.TextField(blank=True, null=True)),
                ('day2_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day2_desc', models.TextField(blank=True, null=True)),
                ('day3_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day3_desc', models.TextField(blank=True, null=True)),
                ('day4_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day4_desc', models.TextField(blank=True, null=True)),
                ('day5_title', models.CharField(blank=True, max_length=50, null=True)),
                ('day5_desc', models.TextField(blank=True, null=True)),
                ('day6_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day6_desc', models.TextField(blank=True, null=True)),
                ('day7_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day7_desc', models.TextField(blank=True, null=True)),
                ('day8_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day8_desc', models.TextField(blank=True, null=True)),
                ('day9_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day9_desc', models.TextField(blank=True, null=True)),
                ('day10_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day10_desc', models.TextField(blank=True, null=True)),
                ('day11_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day11_desc', models.TextField(blank=True, null=True)),
                ('day12_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day12_desc', models.TextField(blank=True, null=True)),
                ('day13_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day13_desc', models.TextField(blank=True, null=True)),
                ('day14_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day14_desc', models.TextField(blank=True, null=True)),
                ('day15_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day15_desc', models.TextField(blank=True, null=True)),
                ('day16_title', models.CharField(blank=True, max_length=200, null=True)),
                ('day16_desc', models.TextField(blank=True, null=True)),
                ('pkg_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
