# Generated by Django 4.1.5 on 2023-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_confirmbooking_pkg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='cancel',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='confirmbooking',
            name='cancel_reason',
            field=models.TextField(default=''),
        ),
    ]
