# Generated by Django 4.1.5 on 2023-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_confirmbooking_cancel_confirmbooking_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmbooking',
            name='cancel',
            field=models.BooleanField(default=0),
        ),
    ]
