"""
Django settings for telusko project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
# import django_heroku
import dj_database_url
# from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hp65ku5f@h(&1r*vkx7*oc3_kx1&6my73xpg3ec)3hly04l^ux'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'travello.apps.TravelloConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_email_verification', 
    'dashboard.apps.DashboardConfig',
    'accounts.apps.AccountsConfig'
    
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'telusko.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'telusko.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'telusko',
        'USER': 'bharat',
        'PASSWORD': '2503',
        'HOST': 'localhost'
    }
}

db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
# STATICFILES_STORAGE = 'whitenoise.storage.CompressManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
#
#
#
# def verified_callback(user):
#     user.is_active = True
#
#
#
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "DIAN Tours Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "DIAN Tours",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "DIAN Tours",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "images/logo_bg.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "images/admin_logo.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,
     # Welcome text on the login screen
    "welcome_sign": "Welcome to DIAN Tours Admin site",

     # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "images/favicon.ico",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    # Copyright on the footer
    "copyright": "DIAN Tours.com",

    # "search_model": ["auth.User", "auth.Group","travello.confirmbooking"],

    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Packages",  "url": "/admin/travello/packages/", "permissions": ["auth.view_user"]},
        {"name": "Bookings",  "url": "/admin/travello/confirmbooking/", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"name":"Database","app": "travello"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    # "usermenu_links": [
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    #     {"model": "auth.user"}
    # ],

     #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to auto expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": ["travello.packages","travello.confirmbooking","travello.contact","travello.payment"],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "travello": [{
            "name": "Packages", 
            "url": "/admin/travello/packages/", 
            "icon": "fas fa-cube",
            # "icon": "fa-solid fa-cube",
            "permissions": ["travello.view_travello"],
        },
        {
            "name": "Bookins", 
            "url": "/admin/travello/confirmbooking/", 
            "icon": "fas fa-check-square",
            # "icon": "fa-solid fa-cube",
            "permissions": ["travello.view_travello"],
        },
        {
            "name": "Enquiry", 
            "url": "/admin/travello/contact/", 
            "icon": "fas fa-question-circle",
            # "icon": "fa-solid fa-cube",
            "permissions": ["travello.view_travello"],
        },
        {
            "name": "Payments", 
            "url": "/admin/travello/payment/", 
            "icon": "fas fa-rupee-sign",
            # "icon": "fa-solid fa-cube",
            "permissions": ["travello.view_travello"],
        }
        ]
    },

    #  "icons": {
    #     "auth": "fas fa-users-co",
    #     "auth.user": "fas fa-user",
    #     "auth.Group": "fas fa-users",
    # },


}

# EMAIL_ACTIVE_FIELD = 'is_active'
# EMAIL_SERVER = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_ADDRESS = 'priyadhokiya143@gmail.com'
# EMAIL_PASSWORD = 'gddqhwfdoaapnqba'
# EMAIL_FROM_ADDRESS = 'priyadhokiya143@gmail.com'
# EMAIL_MAIL_SUBJECT = 'Confirm your email'
# EMAIL_MAIL_HTML = 'mail_body.html'
# EMAIL_MAIL_PLAIN = 'mail_body.txt'
# EMAIL_TOKEN_LIFE = 60 * 60
# EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
# EMAIL_PAGE_DOMAIN = 'http://mydomain.com/'
#





# EMAIL_VERIFIED_CALLBACK = verified_callback
# EMAIL_FROM_ADDRESS = 'Dian Tours@gmail.com'
# EMAIL_MAIL_SUBJECT = 'Confirm your email'
# EMAIL_MAIL_HTML = 'mail_body.html'
# EMAIL_MAIL_PLAIN = 'mail_body.txt'
# EMAIL_TOKEN_LIFE = 60 * 60
# EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
# EMAIL_PAGE_DOMAIN = 'http://mydomain.com/'

# # For Django Email Backend
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'hitanshuparekh72@student.sfit.ac.in'
# EMAIL_HOST_PASSWORD = 'hitanshu72'  # os.environ['password_key'] suggested
# EMAIL_USE_TLS = True

#SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'diantours2023@gmail.com'
EMAIL_HOST_PASSWORD = 'gohoamxlcukpxkpm' 
DEFAULT_FROM_EMAIL = 'diantours2023@gmail.com'
# EMAIL_HOST_USER = 'priyadhokiya143@gmail.com'
# EMAIL_HOST_PASSWORD = 'gddqhwfdoaapnqba'
# EMAIL_HOST_PASSWORD = 'kkgbyaepzqiiogmu'
# EMAIL_HOST_PASSWORD = 'Diantours@2023'
# EMAIL_ACTIVE_FIELD = 'is_active'

# django_heroku.settings(locals())
# RAZORPAY_API_KEY="rzp_test_8TSdUFj7Vi1gim"
# RAZORPAY_API_SECRET_KEY="Kpn7jdxLjZE5l2C2MSae403k"
CSRF_TRUSTED_ORIGINS = ['https://api.razorpay.com']
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
RAZORPAY_API_KEY="rzp_test_hAaloRIq5Dczf6"
RAZORPAY_API_SECRET_KEY="Mt2sZff99nQsGexVvBWNLJFo"

